#!/usr/bin/env python3
"""Ephemeral noVNC on an isolated X display. 15 min, then tear down."""
from __future__ import annotations

import json
import os
import secrets
import shutil
import signal
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE = Path(os.environ.get("SELL_VNC_STATE", str(ROOT / "data" / "pulse-vnc.json")))
NOVNC_WEB = os.environ.get("SELL_NOVNC_WEB", "/usr/share/novnc")
SNIPPET = Path(
    os.environ.get("SELL_VNC_NGINX_SNIPPET", "/etc/nginx/snippets/sparetoken-pulse-vnc.conf")
)
DISPLAY = os.environ.get("SELL_VNC_DISPLAY", ":99")
RFB_PORT = int(os.environ.get("SELL_VNC_RFB_PORT", "5901"))
WS_PORT = int(os.environ.get("SELL_VNC_WS_PORT", "6081"))


def _nginx_location(nonce: str) -> str:
    return f"""# generated by pulse_vnc.py — do not edit by hand
location /pulse-vnc/{nonce}/ {{
    proxy_pass http://127.0.0.1:{WS_PORT}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_read_timeout 3600s;
    proxy_buffering off;
}}
"""


def public_url(nonce: str, password: str) -> str:
    host = os.environ.get("SELL_VNC_PUBLIC_HOST", "sparetoken.shop")
    return (
        f"https://{host}/pulse-vnc/{nonce}/vnc.html"
        f"?autoconnect=1&reconnect=1&path=pulse-vnc/{nonce}/websockify"
        f"&password={password}"
    )


def _write_nginx(nonce: str) -> None:
    SNIPPET.parent.mkdir(parents=True, exist_ok=True)
    content = _nginx_location(nonce)
    try:
        SNIPPET.write_text(content, encoding="utf-8")
    except PermissionError:
        subprocess.run(
            ["sudo", "-n", "tee", str(SNIPPET)],
            input=content.encode("utf-8"),
            check=True,
            capture_output=True,
        )
    subprocess.run(["sudo", "-n", "nginx", "-t"], check=True, capture_output=True)
    subprocess.run(["sudo", "-n", "systemctl", "reload", "nginx"], check=True, capture_output=True)


def _clear_nginx() -> None:
    empty = "# pulse-vnc idle\n"
    try:
        SNIPPET.write_text(empty, encoding="utf-8")
    except PermissionError:
        subprocess.run(
            ["sudo", "-n", "tee", str(SNIPPET)],
            input=empty.encode("utf-8"),
            check=False,
            capture_output=True,
        )
    subprocess.run(["sudo", "-n", "nginx", "-t"], check=False, capture_output=True)
    subprocess.run(["sudo", "-n", "systemctl", "reload", "nginx"], check=False, capture_output=True)


def start(open_url: str, *, copy_path: Path | None = None) -> dict:
    stop()
    nonce = secrets.token_urlsafe(12).replace("-", "x").replace("_", "y")[:16]
    password = secrets.token_urlsafe(10)
    passfile = ROOT / "data" / f"pulse-vnc-{nonce}.pass"
    passfile.parent.mkdir(parents=True, exist_ok=True)
    passfile.write_text(password + "\n", encoding="utf-8")
    os.chmod(passfile, 0o600)

    procs: list[int] = []
    xvfb = subprocess.Popen(
        ["Xvfb", DISPLAY, "-screen", "0", "1280x720x24", "-ac"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    procs.append(xvfb.pid)
    time.sleep(0.6)
    env = os.environ.copy()
    env["DISPLAY"] = DISPLAY
    if copy_path and copy_path.is_file() and shutil.which("xterm"):
        subprocess.Popen(
            ["xterm", "-hold", "-e", "cat", str(copy_path)],
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    chrome = subprocess.Popen(
        [
            "chromium-browser",
            "--no-first-run",
            "--no-default-browser-check",
            "--disable-gpu",
            "--disable-dev-shm-usage",
            "--no-sandbox",
            "--remote-debugging-port=9222",
            "--remote-debugging-address=127.0.0.1",
            "--remote-allow-origins=*",
            "--user-data-dir=/tmp/sparetoken-sell-chrome",
            open_url,
        ],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    procs.append(chrome.pid)
    vnc = subprocess.Popen(
        [
            "x11vnc",
            "-display",
            DISPLAY,
            "-rfbport",
            str(RFB_PORT),
            "-localhost",
            "-shared",
            "-forever",
            "-passwdfile",
            str(passfile),
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    procs.append(vnc.pid)
    ws = subprocess.Popen(
        [
            "websockify",
            f"127.0.0.1:{WS_PORT}",
            f"127.0.0.1:{RFB_PORT}",
            f"--web={NOVNC_WEB}",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )
    procs.append(ws.pid)
    _write_nginx(nonce)
    state = {
        "nonce": nonce,
        "password": password,
        "pids": procs,
        "passfile": str(passfile),
        "url": public_url(nonce, password),
        "open_url": open_url,
        "started": time.time(),
    }
    STATE.write_text(json.dumps(state), encoding="utf-8")
    os.chmod(STATE, 0o600)
    return state


def stop() -> None:
    if STATE.is_file():
        try:
            state = json.loads(STATE.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            state = {}
        for pid in state.get("pids") or []:
            try:
                os.kill(int(pid), signal.SIGTERM)
            except (OSError, ValueError):
                pass
        pf = state.get("passfile")
        if pf:
            Path(pf).unlink(missing_ok=True)
        STATE.unlink(missing_ok=True)
    _clear_nginx()
    subprocess.run(["pkill", "-f", f"Xvfb {DISPLAY}"], check=False, capture_output=True)
    subprocess.run(["pkill", "-f", f"x11vnc.*-rfbport {RFB_PORT}"], check=False, capture_output=True)
    subprocess.run(["pkill", "-f", f"websockify.*{WS_PORT}"], check=False, capture_output=True)
    subprocess.run(["pkill", "-f", "user-data-dir=/tmp/sparetoken-sell-chrome"], check=False, capture_output=True)


def load_state() -> dict:
    if not STATE.is_file():
        return {}
    try:
        return json.loads(STATE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


if __name__ == "__main__":
    import sys

    cmd = sys.argv[1] if len(sys.argv) > 1 else "stop"
    if cmd == "start":
        target = sys.argv[2] if len(sys.argv) > 2 else "https://dev.to/new"
        print(json.dumps(start(target)))
    else:
        stop()
        print("stopped")
